set -sg escape-time 0
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",*256col*:RGB"
set -g base-index 1
setw -g pane-base-index 1
set -g mouse on
set -g history-limit 10000
set -g set-clipboard on
bind-key -T copy-mode MouseDragEnd1Pane send-keys -X copy-pipe-no-clear "pbcopy"
bind r source-file ~/.tmux.conf \; display "Reloaded!"
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"